In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import os

In [20]:
activity_data = pd.read_csv("Outputs/output_file_acc.csv")
activity_data.head()
activity_data.Profile = pd.Categorical(activity_data.Profile)
activity_data['Profile_code'] = activity_data.Profile.cat.codes
activity_data.Activity = pd.Categorical(activity_data.Activity)
activity_data['Activity'] = activity_data.Activity.cat.codes

clean_data = activity_data.drop("Profile", axis=1)
clean_data = clean_data.drop("Date_time", axis=1)

clean_data["Profile_code"].unique()
#activity_data["Profile"].unique()
clean_data.describe()
clean_data.dtypes
activity_data.head()

,Date_time,X,Y,Z,ts,Profile,Activity,Profile_code
0,2020-01-09 11:17:28.568,0.190048,-0.078262,-0.986176,1578568648,MG,4,5
1,2020-01-09 11:17:28.671,0.140366,-0.068359,-0.998215,1578568648,MG,4,5
2,2020-01-09 11:17:28.772,0.003952,-0.032806,-0.969467,1578568648,MG,4,5
3,2020-01-09 11:17:28.872,-0.010345,0.084564,-0.947189,1578568648,MG,4,5
4,2020-01-09 11:17:28.971,0.116348,-0.303986,-1.067520,1578568648,MG,4,5

In [21]:
# Assign X (data) and y (target)
X = clean_data.drop("Activity", axis=1)
y = clean_data["Activity"]
print(X.shape, y.shape)

(72314, 5) (72314,)

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [23]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [24]:
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [25]:
X_train.head()

              X          Y         Z          ts  Profile_code
21481  0.349350   5.462814  8.197815  1578503520             0
21909  0.349350   5.462814  8.197815  1578503580             0
68780 -0.128189  -0.912155 -0.386810  1578580403             7
37418 -0.748947 -11.837296 -1.261017  1578511560             0
55178 -0.011841   0.098312 -0.992691  1578667069             3

In [26]:
 classifier.fit(X_train, y_train)

C:\Users\mghan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\mghan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [27]:
 LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [28]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.41211394855720473
Testing Data Score: 0.41213562697051825

In [29]:
predictions = classifier.predict(X_test)
print(f"First 10 Predictions:   {predictions[:10]}")
print(f"First 10 Actual labels: {y_test[:10].tolist()}")

First 10 Predictions:   [3 3 3 3 3 3 3 3 3 3]
First 10 Actual labels: [4, 4, 5, 2, 5, 0, 4, 0, 4, 3]

In [16]:
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)

      Prediction   Actual
0        stairsu    stand
1        stairsu    stand
2        stairsu     walk
3        stairsu  stairsd
4        stairsu     walk
5        stairsu   laying
6        stairsu    stand
7        stairsu   laying
8        stairsu    stand
9        stairsu  stairsu
10       stairsu  stairsu
11       stairsu  stairsd
12       stairsu  stairsu
13       stairsu  stairsu
14       stairsu  stairsu
15       stairsu    stand
16       stairsu    stand
17       stairsu  stairsd
18       stairsu     walk
19       stairsu  stairsu
20       stairsu  stairsu
21       stairsu     walk
22       stairsu   laying
23       stairsu  stairsu
24       stairsu     walk
25       stairsu  stairsu
26       stairsu      sit
27       stairsu  stairsu
28       stairsu      sit
29       stairsu    stand
...          ...      ...
18049    stairsu      sit
18050    stairsu      sit
18051    stairsu  stairsu
18052    stairsu  stairsu
18053    stairsu     walk
18054    stairsu  stairsd
18055    stairsu  stairsu
18056    stairsu   laying
18057    stairsu      sit
18058    stairsu  stairsu
18059    stairsu    stand
18060    stairsu  stairsu
18061    stairsu      sit
18062    stairsu      sit
18063    stairsu  stairsd
18064    stairsu   laying
18065    stairsu   laying
18066    stairsu   laying
18067    stairsu  stairsu
18068    stairsu  stairsu
18069    stairsu  stairsu
18070    stairsu    stand
18071    stairsu    stand
18072    stairsu  stairsu
18073    stairsu  stairsu
18074    stairsu  stairsd
18075    stairsu   laying
18076    stairsu     walk
18077    stairsu  stairsu
18078    stairsu  stairsu

[18079 rows x 2 columns]